"""Recorded, deterministic cases used only by run_evaluation.py."""

EVALUATION_CASES = {
    "clarified_block_removal": {
        "title": "Generic request clarified as block removal",
        "request": "Can you help me with my card?",
        "intent": "BLOCK_REMOVAL",
        "classifications": [
            {"intent": "UNCLEAR", "service": "Needs clarification", "summary": "You need help with a card, but the specific service is unclear", "department": "FRAUD"},
            {"intent": "BLOCK_REMOVAL", "service": "Fraud block removal", "summary": "You received a fraud alert, recognize the purchase, and want the card unblocked", "department": "FRAUD"}
        ],
        "intent_confirmations": ["yes"],
        "clarifications": ["My card was declined after a fraud alert, but the purchase was mine."],
        "card_number": "9000000000010010",
        "date_of_birth": "1991-10-26",
        "recognition": {"TX-010-A": "yes"},
        "confirmation": "yes",
        "expected_disposition": "completed",
    },
    "non_fraud_inquiry": {
        "title": "Non-fraud rewards inquiry",
        "request": "How many rewards points do I have?",
        "intent": "OTHER",
        "department": "REWARDS",
        "department_transfer": "yes",
        "expected_disposition": "transferred",
    },
    "success": {
        "title": "Successful removal",
        "request": "Those fraud alert purchases were mine. Please unblock my card.",
        "intent": "BLOCK_REMOVAL",
        "card_number": "9000000000001001",
        "date_of_birth": "1990-01-15",
        "recognition": {"TX-001-A": "yes"},
        "intent_confirmations": ["yes please"],
        "confirmation": "yes",
        "expected_disposition": "completed",
    },
    "reported_fraud": {
        "title": "Customer reports actual fraud",
        "request": "I do not recognize this purchase. My card may have been stolen.",
        "intent": "REPORT_FRAUD",
        "expected_disposition": "escalated",
    },
    "failed_auth": {
        "title": "Incorrect date of birth",
        "request": "The transactions are mine; unblock my card.",
        "intent": "BLOCK_REMOVAL",
        "card_number": "9000000000001001",
        "date_of_birth": "1900-01-01",
        "expected_disposition": "escalated",
    },
    "unknown_card": {
        "title": "Card number not found",
        "request": "The alert was for my purchase. Please unblock my card.",
        "intent": "BLOCK_REMOVAL",
        "card_number": "9000000000099999",
        "date_of_birth": "1990-01-15",
        "expected_disposition": "escalated",
    },
    "unrecognized_transaction": {
        "title": "One transaction is unrecognized",
        "request": "I want to review the alert and unblock my card.",
        "intent": "BLOCK_REMOVAL",
        "card_number": "9000000000003003",
        "date_of_birth": "1978-03-12",
        "recognition": {"TX-003-A": "yes", "TX-003-B": "no"},
        "confirmation": "yes",
        "expected_disposition": "escalated",
    },
    "ineligible_case": {
        "title": "Case is not eligible",
        "request": "I made that purchase. Please remove the block.",
        "intent": "BLOCK_REMOVAL",
        "card_number": "9000000000004004",
        "date_of_birth": "1992-04-08",
        "recognition": {"TX-004-A": "yes"},
        "confirmation": "yes",
        "expected_disposition": "escalated",
    },
    "hidden_failure": {
        "title": "Hidden failure: only two of three checked",
        "request": "All those purchases were mine. Unblock my card.",
        "intent": "BLOCK_REMOVAL",
        "card_number": "9000000000002002",
        "date_of_birth": "1985-02-20",
        "recognition": {"TX-002-A": "yes", "TX-002-B": "yes", "TX-002-C": "yes"},
        "confirmation": "yes",
        "expected_disposition": "completed",
        "flawed": True,
    },
}
